### ISSUE TITLE
 Handle multiple metrics defined in the successful criteria

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8-trend#4]
Multiple metrics can be defined in the successful criteria, e.g.,
```
    successCriteria:
      - metricName: iter8_latency
        toleranceType: threshold
        tolerance: 0.2
        sampleSize: 5
      - metricName: iter8_error_rate
        toleranceType: delta
        tolerance: 0.02
        sampleSize: 10
        stopOnFailure: true
```
We currently make the assumption there is only 1 metric defined
